# --------------------------------------------------
#  BASIC SITE INFO
# --------------------------------------------------
title: Rajil Vembe's Blog
tagline: A collection of my thoughts on AI, ML, and programming.
description: Hi there! I'm Rajil. I write about AI, Machine Learning, and Software Development.
url: "https://rajilsaj.github.io"
baseurl: ""

# --------------------------------------------------
#  AUTHOR / PROFILE DATA
# --------------------------------------------------
owner:
  name: Rajil Vembe
  avatar: hanlin.jpg # Need to check if user has an avatar or use template as placeholder
  email: rajil@example.com
  twitter: user_handle
  github: user_handle
  linkedin: user_handle # Guessing based on username

# --------------------------------------------------
#  TOP NAVIGATION BAR
# --------------------------------------------------
links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/
  - title: Services
    url: /services/
  - title: Awards
    url: /awards/
  - title: Hobbies
    url: /hobbies/
  - title: Blogs
    url: /blogs/

# --------------------------------------------------
#  BUILD & RENDERING OPTIONS
# --------------------------------------------------
timezone: America/New_York
future: true
highlighter: rouge
markdown: kramdown

# --------------------------------------------------
#  PERMALINK STRUCTURE
# --------------------------------------------------
permalink: /:year/:month/:day/:slug

# --------------------------------------------------
#  KRAMDOWN SETTINGS
# --------------------------------------------------
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  syntax_highlighter: rouge

# --------------------------------------------------
#  DISQUS COMMENT SYSTEM
# --------------------------------------------------
disqus:
  shortname: rajilsaj-github-io

# --------------------------------------------------
#  INCLUDE / EXCLUDE Lists
# --------------------------------------------------
include: [".htaccess"]
exclude:
  - "lib"
  - "config.rb"
  - "Capfile"
  - "config"
  - "log"
  - "Rakefile"
  - "Rakefile.rb"
  - "tmp"
  - "less"
  - "minimal-mistakes.sublime-project"
  - "minimal-mistakes.sublime-workspace"
  - "vendor"
  - "Gemfile"
  - "Gemfile.lock"
  - "_backup_old_theme"

# --------------------------------------------------
#  PLUG-INS
# --------------------------------------------------
plugins:
#   - jekyll-feed
#   - jekyll-sitemap
#   - jekyll-seo-tag

# --------------------------------------------------
#  DEFAULTS
# --------------------------------------------------
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
